### ISSUE TITLE
Link Fast/Slow actions in combat tracker with token statuses

### ISSUE THREAD

**Issue by phenomen** [fvtt-fria-ligan/yearzero-combat-fvtt#25]
### Description

In YZE Actions module when you click on fast/slow action in the tracker, it also adds/removes a status icon on a token. In YZE Combat those are not synced and you have to manually add statuses.

### Suggested solution

Implement the same behavior as in YZE Actions module.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
Actually, this suggested behavior is conflicting with the duplicate combatant option.

_E.g: Add the status icon to a token, and all combatants and duplicates linked to that token will get the status icon. Which is an issue if your duplicate representing another initiative card for that token has not acted yet._

A solution could be to add a setting option that allows the GM to choose this behavior anyway.

**Comment by lordyod** [comment]
Are duplicate combatants particularly common? This feature is something I would use for every combatant in every combat.

**Comment by Stefouch** [comment]
> Are duplicate combatants particularly common? This feature is something I would use for every combatant in every combat.

Yes. Duplicate combatant is mainly used for monsters with multiple speed/initiative/ferocity : It's used in Forbidden Lands, ALIEN RPG, Dragonbane, and some in Mutant Year Zero.
