### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by retrodans** [fvtt-fria-ligan/yearzero-combat-fvtt#26]
### Describe the bug

I am trying to install the module, but although the messages imply it has installed, it has not.

![Screenshot from 2023-03-16 20-10-33](https://user-images.githubusercontent.com/259789/225741540-4e72090b-5cf1-4ada-8057-f72373e73fcd.png)

Is the "compatibleGameVersion" message something that could be preventing things from installing?

As a bit of context, I am using ForgeVTT. Afraid I had to check all the checkboxes on this form, as they appear to be about it's functionality, but this issue is before that, as I cannot install it at all.

### Reproduction

Not sure, it happens everytime for me on ForgeVTT when I try to install it.

### System Info

```sh
OS: Ubuntu
Client: Chrome
Foundry version: 9
```

### Logs

Nothing appeared in the the logs outside of the normal foundry logs

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the module).

**Comment by DrOgres** [comment]
Hi. The module requires Foundry to be v10. V9 will not work

**Comment by retrodans** [comment]
Ah okay, sorry about not spotting that, will look into updating things, and will try again.
