### ISSUE TITLE
Add setting for new initiative each round

### ISSUE THREAD

**Issue by tak5haka** [fvtt-fria-ligan/yearzero-combat-fvtt#27]
### Description

In preparation for the Dragonbane game, it would be nice to have an optional setting for a new initiative draw each round, as per the core rules. In addition, a setting needs to be considered to take into account the heroic ability "Veteran", which allows a character to keep their original card. I think there also needs to be something in place to take into account the ability for participants to choose their card, as per the "surprise" rules.

### Suggested solution

Perhaps add the "new draw each round" option to the main settings and the others in the drop-down menu for each character?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aMediocreDad** [comment]
PR above only solves initiative each round. Closing this as it is the title of the Issue. Moving the two remaining requests to separate issues.
